"""Markdown rendering for brief output."""

from .schemas import BriefOutput


def render_markdown(brief: BriefOutput) -> str:
    """
    Render a BriefOutput to formatted markdown.

    Args:
        brief: Validated brief data

    Returns:
        Formatted markdown string
    """
    lines = []

    # Title
    lines.append(f"# Company Brief: {brief.ticker}")
    lines.append(f"**Date:** {brief.date}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    for bullet in brief.summary_bullets:
        lines.append(f"- {bullet}")
    lines.append("")

    # Company Snapshot
    lines.append("## Company Snapshot")
    lines.append(f"- **Ticker:** {brief.ticker}")
    lines.append(f"- **Brief Date:** {brief.date}")
    lines.append("")

    # IR Releases
    lines.append("## IR Releases")
    if brief.ir_releases:
        for ir in brief.ir_releases[:3]:  # Top 3
            lines.append(f"### {ir.title}")
            lines.append(f"- **Date:** {ir.date}")
            lines.append(f"- **Source:** {ir.source}")
            if ir.summary:
                lines.append(f"- {ir.summary}")
            lines.append(f"- [Link]({ir.url})")
            lines.append("")
    else:
        lines.append("*No IR releases available.*")
        lines.append("")

    # News Highlights
    lines.append("## News Highlights")
    if brief.news:
        for news in brief.news[:5]:  # Top 5
            lines.append(f"### {news.title}")
            lines.append(f"- **Source:** {news.source}")
            if news.summary:
                lines.append(f"- {news.summary}")
            lines.append(f"- [Link]({news.url})")
            lines.append("")
    else:
        lines.append("*No news items available.*")
        lines.append("")

    # Key Drivers
    lines.append("## Key Drivers")
    for driver in brief.drivers:
        lines.append(f"- {driver}")
    lines.append("")

    # Risks
    lines.append("## Risks")
    for risk in brief.risks:
        lines.append(f"- {risk}")
    lines.append("")

    # Notes & Limitations
    lines.append("## Notes & Limitations")
    for limitation in brief.limitations:
        lines.append(f"- {limitation}")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by IR & News Brief Agent*")

    return "\n".join(lines)
